Redid whole zsh theming

diff --git a/setup_mac b/setup_mac
--- a/setup_mac
+++ b/setup_mac
@@ -1,36 +1,40 @@
 #!/usr/bin/env bash
 
+RED=$(tput setaf 1)
+BLUE=$(tput setaf 4)
+NORMAL=$(tput sgr0)
+
 # Install Homebrew
-echo "Installing Homebrew because this machine didn't come packaged with it for some crazy reason..."
-# which -s brew
-# if [[ $? != 0 ]] ; then
-#    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-# fi
+printf "\n%s\n" "${BLUE}This machine is missing Homebrew. Fixing now...${NORMAL}"
+which -s brew
+if [[ $? != 0 ]] ; then
+   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+fi
 
 # Update Homebrew and install packages
-echo "Updating Homebrew..."
-#brew update
-echo "Tapping caskroom/versions..."
-# brew tap caskroom/versions
-echo "Running brew bundle - installing brew packages..."
-printf '%b\n' "$(cat brew)"
-# brew bundle
+printf  "\n%s\n" "${BLUE}Updating Homebrew...${NORMAL}"
+brew update
+printf "\n%s\n" "${BLUE}Tapping caskroom/versions...${NORMAL}"
+brew tap caskroom/versions
+printf "\n%s\n" "${BLUE}Running brew bundle - installing brew packages...${NORMAL}"
+printf "\n%s\n" "${BLUE}$(cat Brewfile)${NORMAL}"
+brew bundle
 
 # If this user's login shell is not already "zsh", attempt to switch.
-# TEST_CURRENT_SHELL=$(expr "$SHELL" : '.*/\(.*\)')
-# if [ "$TEST_CURRENT_SHELL" != "zsh" ]; then
-#     printf "${BLUE}Changing your default shell to zsh since it's not the 80's anymore and we aren't barbarians.${NORMAL}\n"
-#     chsh -s $(grep /zsh$ /etc/shells | tail -1)
-#     env zsh -l
-# fi
+TEST_CURRENT_SHELL=$(expr "$SHELL" : '.*/\(.*\)')
+if [ "$TEST_CURRENT_SHELL" != "zsh" ]; then
+    printf "\n%s\n"  "${BLUE}Changing your default shell to zsh since it's not the 80's anymore and we aren't barbarians.${NORMAL}"
+    chsh -s $(grep /zsh$ /etc/shells | tail -1)
+    env zsh -l
+fi
 
-# # Download latest copy of antigen file (if non exists currently)
-# ANTIGEN=/antigen.zsh
-# if test ! -f "$ANTIGEN"; then
-#     printf "${BLUE}Installing antigen - the ZSH plugin manager.${NORMAL}\n"
-# 	curl -L git.io/antigen > antigen.zsh
-# fi
+# Download latest copy of antigen file (if non exists currently)
+ANTIGEN=/antigen.zsh
+if test ! -f "$ANTIGEN"; then
+    printf "\n%s\n" "${BLUE}Installing antigen - the ZSH plugin manager.${NORMAL}"
+	curl -L git.io/antigen > antigen.zsh
+fi
 
-# printf "${BLUE}Running dotfiles installation.${NORMAL}\n"
-# # Symbolically link all dotfiles
-# ~/.dotfiles/install_dotfiles
+printf "\n%s\n"  "${BLUE}Running dotfiles installation.${NORMAL}\n"
+# Symbolically link all dotfiles
+~/.dotfiles/install_dotfiles
